# inherit_from: rubocop-todo.yml

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# begin, class, def, end, module と同じ行のコメントを禁止しない
CommentedKeyword:
  Enabled: false

# 行の文字数を制限しない
LineLength:
  Enabled: false

# ブロックの行数を制限しない
BlockLength:
  Enabled: false

# メソッドの行数を制限しない
MethodLength:
  Enabled: false

# クラスの行数を制限しない
ClassLength:
  Enabled: false

# モジュールの行数を制限しない
ModuleLength:
  Enabled: false

# クラスやモジュールの先頭コメントを要求しない
Documentation:
  Enabled: false

# 'set_',  'get_' で始まるアクセサメソッドを許可
AccessorMethodName:
  Enabled: false

# 'is_', 'has_', 'have_' で始まるメソッドを許可
PredicateName:
  Enabled: false

# reduce, injectなど1行でブロック呼び出しした場合の変数名の命名規則を制限しない
SingleLineBlockParams:
  Enabled: false

# 引数の数を制限しない
ParameterLists:
  Enabled: false

# 循環的複雑度を制限しない
CyclomaticComplexity:
  Enabled: false

# Assignment Branch Condition size を制限しない
AbcSize:
  Enabled: false

# Perceived Complexity を制限しない
PerceivedComplexity:
  Enabled: false

# 特定のファイル名をスネークケース以外も許可
# FileName:
#   Exclude:
#     - path/to/file

# ハッシュや配列を複数行で記述する場合、末尾の要素の行末にカンマを付ける
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

# メソッドの引数を複数行で記述する場合、末尾の要素の行末にカンマを付ける
TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# 配列の閉じ括弧のインデントは、開始括弧のある行の先頭に揃える
IndentArray:
  EnforcedStyle: consistent

# ハッシュの閉じ括弧のインデントは、開始括弧のある行の先頭に揃える
IndentHash:
  EnforcedStyle: consistent

# 例外の送出時に raise を利用するか fail を利用するかは文脈に合わせる
SignalException:
  EnforcedStyle: semantic

# クラス指定のないrescue節を禁止しない
RescueWithoutErrorClass:
  Enabled: false

# if 文や case 文全体の返り値を代入するスタイルを強制しない
ConditionalAssignment:
  Enabled: false

# コレクション系メソッドの統一チェックを有効化(ただし inject は修正対象外にする)
CollectionMethods:
  Enabled: true
  PreferredMethods:
    inject: 'inject'

AllCops:
  TargetRubyVersion: 2.1
  # Exclude:
  #   - path/to/exclude/**/*
