# inherit_from: rubocop-todo.yml

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# begin, class, def, end, module と同じ行のコメントを禁止しない
Style/CommentedKeyword:
  Enabled: false

# 行の文字数を制限しない
Layout/LineLength:
  Enabled: false

# ブロックの行数を制限しない
Metrics/BlockLength:
  Enabled: false

# メソッドの行数を制限しない
Metrics/MethodLength:
  Enabled: false

# クラスの行数を制限しない
Metrics/ClassLength:
  Enabled: false

# モジュールの行数を制限しない
Metrics/ModuleLength:
  Enabled: false

# クラスやモジュールの先頭コメントを要求しない
Style/Documentation:
  Enabled: false

# 'set_',  'get_' で始まるアクセサメソッドを許可
Naming/AccessorMethodName:
  Enabled: false

# 'is_', 'has_', 'have_' で始まるメソッドを許可
Naming/PredicateName:
  Enabled: false

# reduce, injectなど1行でブロック呼び出しした場合の変数名の命名規則を制限しない
Style/SingleLineBlockParams:
  Enabled: false

# 引数の数を制限しない
Metrics/ParameterLists:
  Enabled: false

# 循環的複雑度を制限しない
Metrics/CyclomaticComplexity:
  Enabled: false

# Assignment Branch Condition size を制限しない
Metrics/AbcSize:
  Enabled: false

# Perceived Complexity を制限しない
Metrics/PerceivedComplexity:
  Enabled: false

# 特定のファイル名をスネークケース以外も許可
# FileName:
#   Exclude:
#     - path/to/file

# 配列を複数行で記述する場合、末尾の要素の行末にカンマを付ける
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# ハッシュを複数行で記述する場合、末尾の要素の行末にカンマを付ける
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# メソッドの引数を複数行で記述する場合、末尾の要素の行末にカンマを付ける
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# 配列の閉じ括弧のインデントは、開始括弧のある行の先頭に揃える
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# ハッシュの閉じ括弧のインデントは、開始括弧のある行の先頭に揃える
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# 例外の送出時に raise を利用するか fail を利用するかは文脈に合わせる
Style/SignalException:
  EnforcedStyle: semantic

# クラス指定のないrescue節を禁止しない
Style/RescueStandardError:
  Enabled: false

# if 文や case 文全体の返り値を代入するスタイルを強制しない
Style/ConditionalAssignment:
  Enabled: false

# コレクション系メソッドの統一チェックを有効化(ただし inject は修正対象外にする)
Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    inject: 'inject'

# sprintf フォーマットの引数指定形式をチェックしない
Style/FormatStringToken:
  Enabled: false

# shebang(ファイル先頭の#!)があるファイルへの実行権限の付与を強制しない
Lint/ScriptPermission:
  Enabled: false

# Yoda Condition (`if 42 == hoge` のような、変数を右側に置く書き方) を強制しない
Style/YodaCondition:
  Enabled: false

# ガード節のあとの空行を強制しない
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# 後置if/unlessを強制しない
Style/IfUnlessModifier:
  Enabled: false

# ハッシュの位置揃えスタイルの指定(キーの先頭と値の先頭の両方を揃えても許可する)
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/git-diff-normal-format
